### ISSUE TITLE
When will the source code be released?

### ISSUE THREAD

**Issue by hzlhzlhzlhzl** [networkslab/CKGConv#1]
Hello! I am very interested in your impressive and amazing work after reading your paper!
I wonder when will you release your source code because it seems amazing!

Thank you!

**Comment by LiamMa** [comment]
> Hello! I am very interested in your impressive and amazing work after reading your paper! I wonder when will you release your source code because it seems amazing!
> 
> Thank you!

Sorry for missing the opened issue. The code was released in Aug. 

Let me know if you have any question regarding the code.

Best regards,
Liheng
